source("util.R")
data <- readData()
png("plot4.png")
par(mfcol = c(2,2))
with(data, {
     plot(Time, Global_active_power, type="l", xlab="", ylab="Global Active Power")
     plot(Time, Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
     lines(Time, Sub_metering_1)
     lines(Time, Sub_metering_2, col="red")
     lines(Time, Sub_metering_3, col="blue")
     legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n")
     plot(Time, Voltage, type="l", xlab="datetime")
     plot(Time, Global_reactive_power, type="l", xlab="datetime")
})
dev.off()
Sys.setlocale("", category="LC_ALL")
